export const ConditionData = [
  "Abdomen",
  "Abscesses",
  "Acidity",
  "Adenoids",
  "Acne",
  "Allergies",
  "Angina Pectoris",
  "Anti biotic",
  "Apathe",
  "Arthritis",
  "Asthma",
  "Backache",
  "Bad Breath",
  "Bed Wetting",
  "Bites",
  "Bleeding - External",
  "Bleeding - Internal",
  "Bleeding - Gums",
  "Bleeding - Nose",
  "Bladder",
  "Blisters",
  "B.P. High",
  "B. P. Low",
  "Boils",
  "Bone Injuries",
  "Bronchitis",
  "Burns",
  "Carbuncle",
  "Catarrh",
  "Chicken Pox",
  "Chilblains",
  "Cholera",
  "Colic",
  "Collapse",
  "Concentration",
  "Conjunctivitis",
  "Constipation",
  "Cough",
  "Coronary Thrombosis",
  "Cramp",
  "Croup",
  "Cuts",
  "Cystitis",
  "Dandruff",
  "Depression",
  "Diarrhea",
  "Dysentery",
  "Earache",
  "Eructation",
  "Exposure",
  "Eczema",
  "Exhaustion",
  "Eyes",
  "Fainting",
  "Fat, Overweight",
  "Fear",
  "Fever",
  "Fissures - Anal",
  "Fits",
  "Flatulence",
  "Flu and Cold",
  "Food Poisoning",
  "Fracture",
  "Gout",
  "Gums",
  "Gall Bladder",
  "Haemorrhoids",
  "Hay Fever",
  "Headache",
  "Heartburn",
  "Heart Tonic",
  "Herpes",
  "Hiccup/Hiccough",
  "Hot Flashes",
  "Housemaid's Knee",
  "Indigestion",
  "Inflammation - Gums",
  "Influenza",
  "Injuries",
  "Insomnia",
  "Itching Eyes",
  "Itching Body",
  "Joints",
  "Jaundice",
  "Knee - Housemaid's",
  "Laryngitis",
  "Ligaments - Painful",
  "Lumbago",
  "Menstrual Pain",
  "Menstrual Problems",
  "Motion Sickness",
  "Mouth (Taste)",
  "Muscular Pain",
  "Nausea",
  "Neuralgia",
  "Operation",
  "Overweight",
  "Periods",
  "Piles",
  "Pneumonia",
  "Prostrate",
  "Pyorrhea",
  "Rheumatism",
  "Scalds",
  "Sciatica",
  "Shingles",
  "Shock",
  "Sinus",
  "Sneezing",
  "Sprains",
  "Swelling",
  "Styes",
  "Synovitis",
  "Throat (Sore)",
  "Thrush (Mouth)",
  "Tinnitus",
  "Tiredness",
  "Tonsillitis",
  "Toothache",
  "Urinary Problems",
  "Urticaria",
  "Varicose Veins",
  "Vertigo",
  "Vomiting",
  "Warts",
  "Wheezing",
  "Whooping Cough",
  "Worms",
];
